#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# also add other subdomains to make our life easier,
# and write a Bash script that will display information about subdomains

# Define function to display subdomain info
display_subdomain_info() {
    sub_domain=$1
    domain=$2
    record_type=$(dig +short $sub_domain.$domain | awk -F '\t' '{print $2}')
    destination=$(dig +short $sub_domain.$domain)
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Check if both arguments are provided
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Set variables
domain=$1

# Display info for default subdomains when only domain parameter is provided using equals to
if [[ $# -eq 1 ]]; then
    display_subdomain_info "www" $domain
    display_subdomain_info "lb-01" $domain
    display_subdomain_info "web-01" $domain
    display_subdomain_info "web-02" $domain
    exit 0
fi

# Display info for specified subdomain when both domain and subdomain parameters are provided equal to
if [[ $# -eq 2 ]]; then
    sub_domain=$2
    display_subdomain_info $sub_domain $domain
    exit 0
fi
