#!/usr/bin/env bash
# installs nginx on new server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "20i\add_header X-Served-By: $HOSTNAME ;" /etc/nginx/nginx.conf
sudo service nginx restart
