#!/usr/bin/env bash
# installs nginx on new server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i "20i\add_header X-Served-By: $HOSTNAME ;" /etc/nginx/sites-enabled/default;
service nginx start
