#!/usr/bin/env bash
#install and configure HAProxy on load balancer server
sudo apt-get update
sudo apt-get install -y haproxy

configuration=\
"
frontend  load_balancer
        bind *:80
        mode http
        default_backend l_b
backend l_b
        balance roundrobin
        server 86897-web-01 18.204.13.78:80 check
        server 86897-web-02 54.146.77.217:80 check
"
echo "$configuration" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
