#!/usr/bin/env bash
#DESCRIPTION: It loops from one to 10 and it displays bad luck in the 4th
#   loop ,good luck for the 8th loop and Best school for the other iterations.

word=1

while ((word <= 10))
do
        if [ "$word" == 4 ]
        then
                echo bad Luck
                 elif [ "$word" == 8 ]
                then
                        echo good luck
                 else echo Best School
        fi
        word=$((word+1))
done
