#!/usr/bin/env bash
#A script that dispalys the time for 12hrs(from 0-12) and 59 minutes(1-59)
#respectively.

hour=0
minutes=1

while ((hour <= 12))
do
        echo Hour: $hour
        while ((minutes < 60))
        do
                echo $minutes
                minutes=$((minutes+1))
        done
        minutes=1
        hour=$((hour+1))
done
